name: My App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Minikube
      uses: appleboy/minikube-action@v1.6.0
      with:
        minikube_version: 'latest'
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: myapp:${{ github.sha }}
    - name: Load Docker image into Minikube
      run: |
        eval $(minikube docker-env)
        docker load < myapp.tar
    - name: Deploy to Minikube
      run: |
        kubectl apply -f autoscaling.yaml

