name: Apply Kubernetes Deployment

on:
  push:
    branches:
      - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
        
    - name: Deploy to Kubernetes
      uses: appleboy/kubectl-action@master
      with:
        args: apply -f autoscaling.yaml
      env:
        KUBECONFIG: /home/davit_h/k8s-Horizontal-Pod-Autoscaler/kubeconfig.yaml

        


